branches: [main]
tagFormat: "v${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"
analyzeCommits:
  releaseRules:
    - type: feat
      release: minor
    - type: fix
      release: patch
    - type: docs
      release: patch
    - type: perf
      release: patch
    - type: refactor
      release: patch
    - type: breaking
      release: major
    - type: chore
      release: patch

