# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morama < Formula
  desc "A CLI tool for managing your watched movies and dramas"
  homepage "https://github.com/kiku99/morama"
  version "1.1.2"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kiku99/morama/releases/download/v1.1.2/morama_1.1.2_darwin_amd64.tar.gz"
      sha256 "d94bba9a5478a4ce905c61afffbb5b25d95f262304c90fbe3ebb843a6185da6c"

      def install
        bin.install "morama"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kiku99/morama/releases/download/v1.1.2/morama_1.1.2_darwin_arm64.tar.gz"
      sha256 "2a5426d6585f677a6d9af9dc82b678c327b4095a85242c6d97b666826ed514ac"

      def install
        bin.install "morama"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kiku99/morama/releases/download/v1.1.2/morama_1.1.2_linux_amd64.tar.gz"
      sha256 "83f328bd1d5890fd151fb8389667f8b9c279388c1579f34983de2df33053ced6"
      def install
        bin.install "morama"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kiku99/morama/releases/download/v1.1.2/morama_1.1.2_linux_arm64.tar.gz"
      sha256 "96bee34dc202f4a1f07156114f60a9d6e69e0ab2235bc57c332955df203ee5be"
      def install
        bin.install "morama"
      end
    end
  end

  test do
    system "#{bin}/morama", "version"
  end
end
