# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morama < Formula
  desc "A CLI tool for managing your watched movies and dramas"
  homepage "https://github.com/kiku99/morama"
  version "1.1.5"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kiku99/morama/releases/download/v1.1.5/morama_1.1.5_darwin_amd64.tar.gz"
      sha256 "5942030eb86b2f4b4bf7dd1786ede067f1e8da2ce32c211028441a11e0b9fed1"

      def install
        bin.install "morama"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kiku99/morama/releases/download/v1.1.5/morama_1.1.5_darwin_arm64.tar.gz"
      sha256 "c2d88683564d11045eb51578f51a8a6e77c872566e73e14161b7cf2d2e2f9a97"

      def install
        bin.install "morama"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kiku99/morama/releases/download/v1.1.5/morama_1.1.5_linux_amd64.tar.gz"
      sha256 "046e1e87348269cedae5503d09e28ae5f2d49f616c63a612cab86a3905e0b246"
      def install
        bin.install "morama"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kiku99/morama/releases/download/v1.1.5/morama_1.1.5_linux_arm64.tar.gz"
      sha256 "678af780906a7a2f21f44300fc5eadbdd206df762ed45c877874c56ca892f83e"
      def install
        bin.install "morama"
      end
    end
  end

  test do
    system "#{bin}/morama", "version"
  end
end
