# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morama < Formula
  desc "A CLI tool for managing your watched movies and dramas"
  homepage "https://github.com/kiku99/morama"
  version "1.1.3"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kiku99/morama/releases/download/v1.1.3/morama_1.1.3_darwin_amd64.tar.gz"
      sha256 "598a183559f73f256305519667abf440416296b025d0cfe64ba7a335e39afb00"

      def install
        bin.install "morama"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kiku99/morama/releases/download/v1.1.3/morama_1.1.3_darwin_arm64.tar.gz"
      sha256 "55706d5d2bb711fac238405c3d25ce080297139469e8f6005a1daf0a315092b0"

      def install
        bin.install "morama"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kiku99/morama/releases/download/v1.1.3/morama_1.1.3_linux_amd64.tar.gz"
      sha256 "a2ee7681544fc66fa327a7033ed3f704643691bc64d062f8828ebb674edc3130"
      def install
        bin.install "morama"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kiku99/morama/releases/download/v1.1.3/morama_1.1.3_linux_arm64.tar.gz"
      sha256 "b69156f8cfef075a278e9b48f467f23f2d2f821058af13534b3727fb1dced77d"
      def install
        bin.install "morama"
      end
    end
  end

  test do
    system "#{bin}/morama", "version"
  end
end
